// Package initgen generates the shell init file sourced by the user's rc file.
// The generated init.sh sources DAG-ordered script nodes and prepends the
// managed bin directory to PATH (when non-empty).
//
// Generated file is POSIX-compatible: uses "." not "source", single-quotes
// paths using the '\"'\"' idiom to handle spaces and special characters.
package initgen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/rocne/dot-dagger/internal/fileset"
)

// Generate returns the content of an init.sh for the given DAG-ordered nodes.
// binDir, if non-empty, is prepended to PATH. Paths in the output are
// single-quoted so they survive embedding in POSIX sh.
func Generate(nodes []fileset.Node, binDir string) []byte {
	var b strings.Builder

	b.WriteString("# Generated by dot-dagger — do not edit by hand.\n")
	b.WriteString("# Re-generate with: dotd apply\n\n")

	if binDir != "" {
		// Use ${HOME}-relative path when binDir is under home dir.
		quoted := singleQuote(binDir)
		b.WriteString(fmt.Sprintf("PATH=%s:\"${PATH}\"\nexport PATH\n\n", quoted))
	}

	for _, n := range nodes {
		b.WriteString(fmt.Sprintf(". %s\n", singleQuote(n.Path)))
	}

	return []byte(b.String())
}

// WriteFile writes content to path atomically (temp file + rename).
// Creates parent directories as needed.
func WriteFile(path string, content []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("initgen: mkdir %s: %w", filepath.Dir(path), err)
	}

	// Write to a temp file in the same directory so rename is atomic.
	tmp, err := os.CreateTemp(filepath.Dir(path), ".init-*.sh.tmp")
	if err != nil {
		return fmt.Errorf("initgen: create temp: %w", err)
	}
	tmpPath := tmp.Name()

	if _, err := tmp.Write(content); err != nil {
		tmp.Close()
		os.Remove(tmpPath)
		return fmt.Errorf("initgen: write temp: %w", err)
	}
	if err := tmp.Close(); err != nil {
		os.Remove(tmpPath)
		return fmt.Errorf("initgen: close temp: %w", err)
	}

	if err := os.Rename(tmpPath, path); err != nil {
		os.Remove(tmpPath)
		return fmt.Errorf("initgen: rename to %s: %w", path, err)
	}
	return nil
}

// singleQuote returns s wrapped in POSIX single quotes using the '\"'\"' idiom
// to handle any embedded single quotes.
func singleQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "'\\''") + "'"
}
