package pipeline

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// GenerateOptions configures init.sh generation.
type GenerateOptions struct {
	BinDir string // if non-empty, prepended to PATH in init.sh
}

// Generate writes init.sh to path from the ordered list of nodes to source.
// Uses POSIX ". path" syntax with single-quoted paths.
// Writes atomically via temp file + rename.
func Generate(path string, nodes []RawNode, opts GenerateOptions) error {
	content := buildInitSh(nodes, opts)
	return writeAtomic(path, []byte(content))
}

func buildInitSh(nodes []RawNode, opts GenerateOptions) string {
	var b strings.Builder
	b.WriteString("# Generated by dot-dagger — do not edit by hand.\n\n")
	if opts.BinDir != "" {
		fmt.Fprintf(&b, "export PATH=\"%s:${PATH}\"\n\n", opts.BinDir)
	}
	for _, n := range nodes {
		fmt.Fprintf(&b, ". %s\n", singleQuote(n.Path))
	}
	return b.String()
}

func singleQuote(s string) string {
	// Escape single quotes inside the string using the '"'"' idiom.
	return "'" + strings.ReplaceAll(s, "'", "'\"'\"'") + "'"
}

func writeAtomic(path string, content []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("initgen: mkdir: %w", err)
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), ".init-*.sh.tmp")
	if err != nil {
		return fmt.Errorf("initgen: create temp: %w", err)
	}
	tmpPath := tmp.Name()
	if _, err := tmp.Write(content); err != nil {
		_ = tmp.Close()
		_ = os.Remove(tmpPath)
		return fmt.Errorf("initgen: write: %w", err)
	}
	if err := tmp.Close(); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("initgen: close temp: %w", err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("initgen: rename: %w", err)
	}
	return nil
}
