package pipeline

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerate_BasicSourceOrder(t *testing.T) {
	dir := t.TempDir()
	nodes := []RawNode{
		{Path: "/dots/a.sh", LogicalName: "a"},
		{Path: "/dots/b.sh", LogicalName: "b"},
	}
	out := filepath.Join(dir, "init.sh")
	if err := Generate(out, nodes, GenerateOptions{}); err != nil {
		t.Fatal(err)
	}
	content, err := os.ReadFile(out)
	if err != nil {
		t.Fatal(err)
	}
	s := string(content)
	if !strings.Contains(s, ". /dots/a.sh") {
		t.Errorf("expected source line for a.sh, got:\n%s", s)
	}
	if !strings.Contains(s, ". /dots/b.sh") {
		t.Errorf("expected source line for b.sh, got:\n%s", s)
	}
	aIdx := strings.Index(s, "a.sh")
	bIdx := strings.Index(s, "b.sh")
	if aIdx > bIdx {
		t.Errorf("a.sh should come before b.sh")
	}
}

func TestGenerate_NoNodes_WritesHeader(t *testing.T) {
	dir := t.TempDir()
	out := filepath.Join(dir, "init.sh")
	if err := Generate(out, nil, GenerateOptions{}); err != nil {
		t.Fatal(err)
	}
	content, err := os.ReadFile(out)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(content), "Generated by dot-dagger") {
		t.Errorf("expected header comment, got:\n%s", string(content))
	}
}

func TestGenerate_Atomic(t *testing.T) {
	dir := t.TempDir()
	out := filepath.Join(dir, "init.sh")
	// Write twice — second write should replace atomically.
	nodes1 := []RawNode{{Path: "/dots/a.sh", LogicalName: "a"}}
	nodes2 := []RawNode{{Path: "/dots/b.sh", LogicalName: "b"}}
	if err := Generate(out, nodes1, GenerateOptions{}); err != nil {
		t.Fatal(err)
	}
	if err := Generate(out, nodes2, GenerateOptions{}); err != nil {
		t.Fatal(err)
	}
	content, err := os.ReadFile(out)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(content), "a.sh") {
		t.Error("second generate should replace first")
	}
	if !strings.Contains(string(content), "b.sh") {
		t.Errorf("expected b.sh in second generate, got:\n%s", string(content))
	}
}

func TestGenerate_PrependsBinDir(t *testing.T) {
	dir := t.TempDir()
	out := filepath.Join(dir, "init.sh")
	opts := GenerateOptions{BinDir: "/home/user/.local/bin/dot-dagger"}
	if err := Generate(out, nil, opts); err != nil {
		t.Fatal(err)
	}
	content, err := os.ReadFile(out)
	if err != nil {
		t.Fatal(err)
	}
	s := string(content)
	if !strings.Contains(s, `export PATH="/home/user/.local/bin/dot-dagger:${PATH}"`) {
		t.Errorf("expected PATH line with absolute bin dir, got:\n%s", s)
	}
}

func TestGenerate_NoBinDirSkipsPATH(t *testing.T) {
	dir := t.TempDir()
	out := filepath.Join(dir, "init.sh")
	if err := Generate(out, nil, GenerateOptions{}); err != nil {
		t.Fatal(err)
	}
	content, err := os.ReadFile(out)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(content), "PATH") {
		t.Errorf("expected no PATH line when BinDir empty, got:\n%s", string(content))
	}
}
