name: Release dotp

on:
  push:
    tags:
      - "dotp-v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Set version
        run: |
          echo "VERSION=${GITHUB_REF_NAME#*-}" >> $GITHUB_ENV
          echo "FULL_TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --config .goreleaser/dotp.yaml --clean --skip=validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{ env.VERSION }}
          FULL_TAG: ${{ env.FULL_TAG }}
